# Generated by Django 5.0.1 on 2024-01-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('properties', models.TextField(verbose_name='Свойства')),
                ('ghosts', models.ManyToManyField(related_name='evidences', to='main.ghost', verbose_name='Призракаки')),
            ],
        ),
    ]
