# Generated by Django 5.0.1 on 2024-01-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_evidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['name'], 'verbose_name': 'Улика', 'verbose_name_plural': 'Улики'},
        ),
        migrations.AlterModelOptions(
            name='ghost',
            options={'ordering': ['name'], 'verbose_name': 'Призрак', 'verbose_name_plural': 'Призраки'},
        ),
        migrations.AddField(
            model_name='evidence',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='ghost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='ghosts',
            field=models.ManyToManyField(blank=True, null=True, related_name='evidences', to='main.ghost', verbose_name='Призраки'),
        ),
    ]
