# Generated by Django 5.0.1 on 2024-01-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_evidence_options_alter_ghost_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='ghosts',
        ),
        migrations.AddField(
            model_name='ghost',
            name='evidences',
            field=models.ManyToManyField(blank=True, null=True, related_name='ghosts', to='main.evidence', verbose_name='Улики'),
        ),
    ]
